version: "3.8"

services:
  consulting-room:
    build:
      context: .
      dockerfile: ./src/apps/hospital/consulting-room/Dockerfile
    ports:
      - "3002:3002"
    command: npm run dev -w @ducen/hospital-consulting-room
