name: Consulting room CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID_CONSULTING_ROOM }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_CONSULTING_ROOM }}
on:
  push:
    branches: [main]
    paths:
      - "src/apps/hospital/consulting-room/**"
  pull_request:
    branches: [main]
    types: [opened,synchronize,reopened]
    paths:
      - "src/apps/hospital/consulting-room/**"
  workflow_dispatch:
jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: '20.10.0'
      - name: Install dependencies 📦
        run: npm ci --loglevel=error
      - name: Lint 🔍
        run: npm run lint -w @ducen-clients/consulting-room
      - name: Build 🏗️
        run: npm run build -w @ducen-clients/consulting-room
      - name: Unit tests 🧪
        run: npm run test -w @ducen-clients/consulting-room
      - name: Create env file for E2E tests 🧪
        run: |
            cd ./src/apps/hospital/consulting-room
            touch .env
            echo "${{ secrets.DEV_CONSULTING_ROOM_ENV }}" | base64 --decode > .env
      - name: Start Docker Compose 🐳
        run: docker-compose run --rm -d --service-ports consulting-room
      - name: Wait for API to start
        run: sleep 5
      - name: E2E tests 🧪
        run: npm run test:e2e -w @ducen-clients/consulting-room
  deploy:
    needs: [build]
    runs-on: ubuntu-22.04
    if: ${{ github.ref == 'refs/heads/main'}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull vercel
        run: vercel  pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_CONSULTING_ROOM }}
      - name: Build Vercel Artifact
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_CONSULTING_ROOM }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_CONSULTING_ROOM }}
