name: Core CI

on:
  push:
    branches: [main]
    paths:
      - "src/contexts/shared/core/**"
  pull_request:
    branches: [main]
    types: [opened,synchronize,reopened]
    paths:
      - "src/contexts/shared/core/**"
  workflow_dispatch:
jobs:
  avoid_reduncy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies
        run: npm ci --loglevel=error
      - name: Lint
        run: npm run lint -w core
  sonar:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ github.token }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/contexts/shared/core
  build:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v2
          with:
            cache: 'npm'
            node-version: '16.14.2'
        - name: Install dependencies
          run: npm ci --loglevel=error
        - name: Build
          run: npm run build -w core
  test:
    needs: [lint, build, sonar]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: '16.14.2'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test -w core
